// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbn5oCZgtzV9d1nRR79E2vrz9X-fPyG8o',
    appId: '1:62880664729:web:24ae4d31da42da740abc08',
    messagingSenderId: '62880664729',
    projectId: 'uber-verttran',
    authDomain: 'uber-verttran.firebaseapp.com',
    storageBucket: 'uber-verttran.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApt70hRNVYq326uQCUnz6HaPmEQEqK7X4',
    appId: '1:62880664729:android:5422e96e06ed354e0abc08',
    messagingSenderId: '62880664729',
    projectId: 'uber-verttran',
    storageBucket: 'uber-verttran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDu_mcprgoNV2vKbkgBWexuYL_znhxtCQ',
    appId: '1:62880664729:ios:3df4506d5d8a96c60abc08',
    messagingSenderId: '62880664729',
    projectId: 'uber-verttran',
    storageBucket: 'uber-verttran.firebasestorage.app',
    iosBundleId: 'com.verttran.ubers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDu_mcprgoNV2vKbkgBWexuYL_znhxtCQ',
    appId: '1:62880664729:ios:dc9da7ab8af6bf860abc08',
    messagingSenderId: '62880664729',
    projectId: 'uber-verttran',
    storageBucket: 'uber-verttran.firebasestorage.app',
    iosBundleId: 'com.example.users',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbn5oCZgtzV9d1nRR79E2vrz9X-fPyG8o',
    appId: '1:62880664729:web:ca2d86e2d09e7dc00abc08',
    messagingSenderId: '62880664729',
    projectId: 'uber-verttran',
    authDomain: 'uber-verttran.firebaseapp.com',
    storageBucket: 'uber-verttran.firebasestorage.app',
  );
}
